import struct, random
random.seed(20240601)

def f32(x):
    return struct.unpack('f', struct.pack('f', x))[0]

# Build a list of f32 test values
vals = []
# Edge cases
edge = [0.0, -0.0, 1.0, -1.0, 0.5, -0.5,
        1.000005, 0.000005, -0.000005, 1.0000049, 1.0000051,
        1e-7, 1e-6, 1e-5, 1e-4, 1e20, -1e20, 1e10, -1e10,
        123456.789, 0.123456789, 9999999.0, 0.0000001,
        3.4028235e38, 1.1754944e-38,  # f32 max / min normal
        2.5, 3.5, 0.25, 0.125, 12345.6789,
        100000.0, 99999.99, 1000000.0, 1234567.0,
        0.99999999, 1.5e-5, 2.5e-5, 0.0000015, 0.0000025,
        1.5, 2.5, 0.15, 0.25, 0.35, 1.005, 2.675,  # classic rounding cases
        ]
for e in edge:
    vals.append(f32(e))

# Random values spanning many magnitudes
for _ in range(400):
    # random exponent and mantissa
    exp = random.uniform(-25, 25)
    sign = random.choice([1.0, -1.0])
    m = random.uniform(0.0, 10.0)
    vals.append(f32(sign * m * (10.0 ** exp)))

# Some small integers / counts as floats (common in pileup)
for i in range(0, 60):
    vals.append(f32(float(i)))
    vals.append(f32(i + 0.5))

lines = []
for v in vals:
    # bit pattern (so Rust reads the EXACT same f32), then expected %.5f and %.6g
    bits = struct.unpack('I', struct.pack('f', v))[0]
    s5 = '%.5f' % float(v)   # CPython delegates to C printf with correct rounding
    s6 = '%.6g' % float(v)
    lines.append("%08x\t%s\t%s" % (bits, s5, s6))

out = "/home/kenchen/Documents/macs-rna/rust/macs3-rs/crates/macs3-core/tests/fixtures/fmt_golden.tsv"
with open(out, "w") as fh:
    fh.write("# bits_hex(f32 little-endian as u32)\t%.5f\t%.6g  -- generated by tests/fixtures/gen_fmt_fixture.py with plain CPython\n")
    fh.write("\n".join(lines) + "\n")
print("wrote", len(lines), "rows to", out)
